name: Add File
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  add_test_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          now = $(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "\${now}"
          git push
