name: Hydrangea Info Gatherer
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  add_test_file:
    runs-on: ubuntu-latest
    name: Test File Adding
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5" # Python Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python src/baidu_hot_search.py
          python src/mfc_cn.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          now=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "${now}"
          git push

  pages_directory_listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main #checkout different branch

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v3.0.0
        with:
          FOLDER: . #directory to generate index

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "." # upload generated folder

  deploy:
    name: Deployment
    needs: pages_directory_listing
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1